export const FORM_CONFIGS = {
  detection_defaut: {
    title: "Détection de défaut",
    form_type: "detection_defaut",
    is_nidec: false,
    hasDefaut: true,
    hasCF: true,
    hasDate: false,
    hasQuantite: true,
    required: [
      "bu",
      "ligne",
      "defaut",
      "poste",
      "equipe",
      "nombre",
      "mat_csl1",
      "mat_cf",
    ],
  },

  detection_defaut_nidec: {
    title: "Détection de défaut NIDEC",
    form_type: "detection_defaut",
    is_nidec: true,
    hasDefaut: true,
    hasCF: true,
    hasDate: false,
    hasQuantite: true,
    required: [
      "bu",
      "ligne",
      "defaut",
      "poste",
      "equipe",
      "nombre",
      "mat_csl1",
      "mat_cf",
    ],
  },

  quantite_archive: {
    title: "Quantité archive",
    form_type: "quantite_archive",
    is_nidec: false,
    hasDefaut: false,
    hasCF: false,
    hasDate: true,
    hasQuantite: true,
    required: [
      "date_detection",
      "ligne",
      "bu",
      "poste",
      "equipe",
      "nombre",
      "mat_csl1",
      "quantite_controlee",
    ],
  },

  quantite_archive_nidec: {
    title: "Quantité archive NIDEC",
    form_type: "quantite_archive",
    is_nidec: true,
    hasDefaut: false,
    hasCF: false,
    hasDate: true,
    hasQuantite: true,
    required: [
      "date_detection",
      "ligne",
      "bu",
      "poste",
      "equipe",
      "nombre",
      "mat_csl1",
      "quantite_controlee",
    ],
  },

  archive_defaut: {
    title: "Archive défaut",
    form_type: "archive_defaut",
    is_nidec: false,
    hasDefaut: true,
    hasCF: true,
    hasDate: false,
    hasQuantite: true,
    required: [
      "bu",
      "ligne",
      "defaut",
      "poste",
      "equipe",
      "nombre",
      "mat_csl1",
      "mat_cf",
    ],
  },

  archive_defaut_nidec: {
    title: "Archive défaut NIDEC",
    form_type: "archive_defaut",
    is_nidec: true,
    hasDefaut: true,
    hasCF: true,
    hasDate: false,
    hasQuantite: true,
    required: [
      "bu",
      "ligne",
      "defaut",
      "poste",
      "equipe",
      "nombre",
      "mat_csl1",
      "mat_cf",
    ],
  },
};